version: "3.8"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2:rw

  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - nodered:/data

volumes:
  nodered:
  influxdb:
